### ISSUE TITLE
Add `minimum_views` param to docs for optics_line_text_reducer

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/aggregation-for-caesar#387]
The `minimum_views` parameter, used to determine when a line should be grayed-out in the front-end as part of the transcription tools, does not appear in the function docstring nor the [online docs](https://aggregation-caesar.zooniverse.org/reducers.html#line-tool-with-text-subtask-reducer-using-optics). 

I believe the fix should be added here: https://github.com/zooniverse/aggregation-for-caesar/blob/8b900017b08f5e1ee5f415b3effe037bce4defe1/panoptes_aggregation/reducers/optics_line_text_reducer.py#L101-L102

If that's all that needs to be done, great!  I'd be happy to submit that change as a PR if confirmed.

**Comment by CKrawczyk** [comment]
I was just looking at this today, took me a little bit to remember what it does because in the code it only shows up as:
```_ = kwargs_optics.pop('minimum_views')```
(i.e. it is 100% ignored).

This value is only ever passed along to the final reduction object inside the `parameters` section, it has no effect on the results of the reduction.  

Reason: The front-end uses this value to determine when to grey out a line and this is a convenient way to have it be set on a workflow-by-workflow basis without needing to store any custom values on the panoptes workflow JSON object (also don't need to write a new UI element to set the value).

As it technically does not have a function within the aggregation code I am not really sure this is the best place to document it beyond "this value is passed along to the front-end."

**Comment by lcjohnso** [comment]
The PR looks good, and just noting here that I agree there should be some documentation of how this param is used by the front end code in visualizing the transcribed lines.  Will think about where that documentation belongs -- part of a growing list of patterns where configuration is multi-app in nature.
